### ISSUE TITLE
make OK on windows and KO on travis

### ISSUE THREAD

**Issue by damien7851** [poppy-project/poppy-com#7]
My fork on makingbot compile on windows but not on travis (linux)
Makefile is very complicated.

add   local makefile is an good idea.

**Comment by nicolas-rabault** [comment]
There is a makefile on this repo : https://github.com/poppy-project/poppy_com/blob/master/Makefile
I use it on travis... Your fork is probably behind this makefile!

**Comment by damien7851** [comment]
it was not a Makefile problem but just a case problem because Windows does not differentiate between lower and upper case unlike Linux ...
